<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>SG_BAMS</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.1" />
    <PackageReference Include="Emgu.CV" Version="4.13.0.5924" />
    <PackageReference Include="Emgu.CV.Bitmap" Version="4.13.0.5924" />
    <PackageReference Include="Emgu.CV.runtime.windows" Version="4.13.0.5924" />
    <PackageReference Include="Krypton.Toolkit" Version="105.26.7.201" />
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260627" />
    <PackageReference Include="OpenCvSharp4.Extensions" Version="4.13.0.20260627" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.13.0.20260627" />
    <PackageReference Include="OpenCvSharp4.Windows" Version="4.13.0.20260627" />
    <PackageReference Include="PdfPig" Version="0.1.15" />
    <PackageReference Include="ReaLTaiizor" Version="3.8.2.1" />
    <PackageReference Include="WinForms.DataVisualization" Version="1.10.2" />
    <PackageReference Include="QuestPDF" Version="2026.7.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

<ItemGroup>
  <InternalsVisibleTo Include="SG_BAMS.PruebasCarga" />
</ItemGroup>

<ItemGroup>
  <ProjectReference Include="..\SG_BAMS.AccesoDatos\SG_BAMS.AccesoDatos.csproj" />
  <ProjectReference Include="..\SG_BAMS.Dominio\SG_BAMS.Dominio.csproj" />
  <ProjectReference Include="..\SG_BAMS.LogicaNegocio\SG_BAMS.LogicaNegocio.csproj" />
</ItemGroup>

</Project>